### ISSUE TITLE
[microsite] desktop visual tweaks

### ISSUE THREAD

**Issue by ericronne** [18F/climate-labs#37]
@shawnbot @jeremiak 

I made a few refinements to the desktop view (some of which trickled down to the [mobile view](https://github.com/18F/climate-labs/issues/38))

- New photo: Buffalo(!) struck me as a nice, visually interesting, non-NYC pic (@onezerojeremy, @colinpmacarthur: like?)
- Added a feature to view the presentation (and tweaked layout, and added a "downloads" subhead, which @kategarklavs and others may wish to change)
- Also added a downloads sidebar near the top of the page, for convenience

[Sketch file](https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaQkItdUpLR25kZkE/view?usp=sharing)

Critique welcome, as always!
But assuming this is okay to go, i'll set up a live-tweak session with @shawnbot 

![micrositesm](https://cloud.githubusercontent.com/assets/9259185/14836649/448ccbac-0bd7-11e6-8d23-d1f6014121b7.png)

**Comment by colinpmacarthur** [comment]
Looks good to me!

**Comment by jeremiak** [comment]
Closed in favor of #44
